[package]
name = "engineio"
version = "0.1.0"
authors = ["Moritz Gunz <moritz.gunz@gmail.com>"]
description = "A engine.io client library in Rust"
readme = "README.md"
repository = "https://github.com/NeoLegends/engineio-rs"
keywords = ["engine", "engineio", "engine.io", "socket", "socketio", "socket.io", "websocket"]
license = "MITNFA"

[dependencies]
hyper = { version = "0.9.*", default-features = false }
rustc-serialize = "0.3.*"
url = "0.5.9"
ws = "0.4.*"

[features]
default = []
ssl = ["hyper/ssl", "ws/ssl"]